<a href="https://colab.research.google.com/github/arielwendichansky/DI_Bootcamp/blob/master/Week6/Day5/Exercise_XP/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install numpy
import numpy as np

#🌟 Exercise 1 : Array Creation And Manipulation


In [9]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#🌟 Exercise 2 : Type Conversion And Array Operations
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.



In [10]:
list_1 = [3.14, 2.17, 0, 1, 2]
array = np.array(list_1)
print(array)
print(array.dtype)
array = array.astype(np.uint8)
array

[3.14 2.17 0.   1.   2.  ]
float64


array([3, 2, 0, 1, 2], dtype=uint8)

# 🌟 Exercise 3 : Working With Multi-Dimensional Arrays
Create a 3x3 NumPy array with values ranging from 1 to 9.



In [19]:
matrix = np.arange(1,10).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 🌟 Exercise 4 : Creating Multi-Dimensional Array With Random Numbers
Create a 2D NumPy array of shape (4, 5) filled with random numbers.



In [40]:
array_2d = np.random.rand(1,20).reshape(4,5)
array_2d

array([[0.69039486, 0.44707318, 0.14860725, 0.38175771, 0.8406021 ],
       [0.31492423, 0.61102529, 0.69771122, 0.2268385 , 0.40848971],
       [0.99345337, 0.99035271, 0.62982381, 0.03960141, 0.18673759],
       [0.83744435, 0.04563366, 0.15560808, 0.43561503, 0.06126573]])

#🌟 Exercise 5 : Indexing Arrays
Select the second row from a given 2D NumPy array.



In [43]:
select = array_2d[2]
select

array([0.99345337, 0.99035271, 0.62982381, 0.03960141, 0.18673759])

# 🌟 Exercise 6 : Reversing Elements
Reverse the order of elements in a given 1D NumPy array (first element becomes last).



In [48]:
array = np.arange(10)
reverse_array=array [::-1]
reverse_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#🌟 Exercise 7 : Identity Matrix
Create a 4x4 identity matrix using NumPy.



In [52]:
array_4 = np.eye(4)
array_4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#🌟 Exercise 8 : Simple Aggregate Funcs
Find the sum and average of a given 1D array.



In [53]:
print("Mean:", np.mean(array))
print("Sum:", np.sum(array))

Mean: 4.5
Sum: 45


# 🌟 Exercise 9 : Create Array And Change Its Structure
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.



In [59]:
matrix = np.random.randint(1,20, size = (1,20))
matrix.reshape(4,5)

array([[13, 11, 16, 18,  5],
       [18,  8,  3, 14, 14],
       [19,  4, 11,  2, 11],
       [ 3, 10, 13, 13,  7]])

#🌟 Exercise 10 : Conditional Selection Of Values
Extract all odd numbers from a given NumPy array.



In [61]:
result = array[array % 2 != 0]
result

array([1, 3, 5, 7, 9])